### ISSUE TITLE
How To use 

### ISSUE THREAD

**Issue by lzomedia** [makeabledk/laravel-query-kit#10]
Any Plans on writing docs on how to use this package?

**Comment by rasmuscnielsen** [comment]
Hi @lzomedia 

Though the docs are not super comprehensive I believe they cover basic usage.

For more examples I recommend checking the tests in: https://github.com/makeabledk/laravel-query-kit/blob/master/tests/Unit/QueryScopesTest.php

Also do checkout the more opionated and documented package: https://github.com/makeabledk/laravel-eloquent-status

We're a bit too swamped right to be improving the docs but would be happy for a PR.

Cheers
