### ISSUE TITLE
Add IsJoined feature

### ISSUE THREAD

**Issue by Belkadam** [makeabledk/laravel-query-kit#8]
Hi,

I try to create a fork to add isJoined feature that return true if a instance of a model is joined to another.
For exemple if a user have a car
`$user->car!==null`

But i'm a little bit lost on how to unit test this on QueryScopesTest.
How can I quickly create a car related to a user and respecting the way your unit tests are coded?

Thanks,

**Comment by Belkadam** [comment]
There's no way to add JOIN feature ?

**Comment by rasmuscnielsen** [comment]
Hi @Belkadam 

Thanks for creating this issue.

If I understand the issue correct, I believe this is not a direction we're interested of taking this package. The philosophy of the package is to provide a convenient way of checking your model attributes. 
Dealing with joins (or other SQL queries) would encourage potential n+1 issues and should be avoided.

**Comment by rasmuscnielsen** [comment]
To address your issue:

Perhaps a workaround for you would be to create a scope that adds the attribute on your query:

`Users::withHasCar()->get()` // withHasCar appends an attribute via SQL. Then you can check that as a normal attribute
